language: go
go:
- 1.12.x
env:
- GO111MODULE=on
before_install:
  - go mod vendor
script:
- go build -mod=vendor .
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    repo: faozimipa/monggo